[project]
name = "paytrace-e2e-tests"
version = "0.1.0"
description = "PAYTRC-UTIL-001: Utility project for doing end to end testing of PayTrace's API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "psycopg2-binary>=2.9.10",
  "pytest>=8.3.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
